//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioseca.Web
{


    public partial class _Default
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Biblioseca.Web.SiteMaster Master
        {
            get
            {
                return ((Biblioseca.Web.SiteMaster)(base.Master));
            }
        }
    }
}
