//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioseca.Web.Borrows {
    
    
    public partial class BusinessError {
        
        /// <summary>
        /// BackToList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify, move the field declaration from the designer file to a code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink BackToList;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Biblioseca.Web.SiteMaster Master {
            get {
                return ((Biblioseca.Web.SiteMaster)(base.Master));
            }
        }
    }
}
