# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on: [ push ]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.1

      - name: Nuget Restore
        run: nuget restore Biblioseca.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: msbuild Biblioseca.sln /m /nr:false /t:Build /p:Configuration=Debug /p:Platform="Any CPU" /verbosity:minimal /p:CreateHardLinksForCopyLocalIfPossible=true

#      - name: Test
#        run: packages/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe Biblioseca.Test/bin/Debug/Biblioseca.Test.dll      